travis:
  secure:
    BINSTAR_TOKEN: aQjKmibqV7ObD81UMlw+4pLsYnESPMmu3UaJwH+srER3j3oEfKnSTPYNBxWc+wM2/MUvdauwm7Cp+SpWOfcSCzS1UNzRDn9jMJdPuwiZHsR/sV07zwZacjpRFIUc6Ho6zyZH2V2DsPUwoXcHcOIl6ddt92PNqFyWvBBI+YxRUs2ubt9Zo5Z4WGeYjCsJ/iD0AhmSAho+XPEUF3fJ0YYmLicelYvNfKrVGGWezhp0spVRUlD/k8WYIpuCjPiEYmR71gBcv40PpAff6hcPDusyLwiwaw7AjY2RoBK45y+XKYyBfrhfnriJjIYbp8j8VDGkBHUERpXKBmI9v4H9JL99wOBgONNJF7u/D7At7L7w02E2IjngfiyZYkgBTfoN4UIJLd20lPZ0jwXLU87TC/hML2IfzRYAFoMStf3eeetUFnLRa4Kin1s8hg7Zz0YS90O8CRkZYu+K1zLH8MA1yL000AjcKpoPLSkZ7VIg2czCutuXMtdn7oOLGaa3AuQxEGv1XCADwJ7gL16AohP/iKrkS6JKAOwr7uHN3DChyPiVYpJ8jgYWa8XqXm3NQY3WWcJYOT+Hd0pHsXuMI46dZrZikqTxbAnv6TtVTMrZKfbAg/bBALVqmiPnFt8IWMo61R0MYn4WwAqyF86ae23nvkghHatk9ZhMpkFS3ZATttPgeW0=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
