travis:
  secure:
    BINSTAR_TOKEN: ZNW1M9QDysCCuhT3fnaU6qzTiHWoKOpJHoMnzfYgc3EiDARD4tsISdZIKV3DYUU855AG+8wL6x6ncx7VBvhnU/amvL+jj6LwjpebGFrJnRhpNdPRa0F7qnytJyJcD9n4YCZIdLFXvo3ADWcYCmnUwSlfYxBbBAeBDbzHNW5KZmid9pulNwLbF5b8hQ57KR2l61ou8ZkQGMM/qken6iELDRYcjZTaU/AayKJ81DivghlJvOHciHpy/h5FpZBuNQVkDfZ1iuxjEtBTpWjJravAkcqzhQDxSeuwLSaPqAhssuiX5MZl8r+u/M0LvhBkPYn6LA5SAovVsRv0VHUUGWvpUiEzPTHQwxYbLjqHKDOH5z7D41AIKR/iQLf5xPIOeD69XF3z6UH4xfCAP5wLKO4XGBtwIEekySDWL6tgLpts2a4smnuwgnOcNGB7MxU6RaPZg6Jo9jJ7DEPK9D0Gr9soUxbJesBUHiLlSj4ef40w6f4BnzcYFCSZQkMiZMME/jIqqfjfGrGkdQjy+qocip6VorlWLK6GTKF1FsD8G1r25aRWAPZuQ8+9p7NVluPzrEtliHk+5vfODaxWHGecbUTG+7c/5/ONutn7RIDHiBCpYh2AwsEgizdDUuonx+yRbUOYkf1OecVQ8laPRnHKHuV4J1GKYxkIm9InAcVUDiLjyeg=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
